/** Public HTTP/Desktop wire budgets are owned by collaboration-protocol. */
export {
  HUMAN_ASSIGN_REASON_MAX_LENGTH,
  HUMAN_COMMENT_BODY_MAX_LENGTH,
  HUMAN_DEVICE_LABEL_MAX_LENGTH,
  HUMAN_DEVICE_MAX_TTL_MS,
  HUMAN_DEVICE_MIN_TTL_MS,
  HUMAN_DEVICE_TOKEN_PREFIX,
  HUMAN_IDENTITY_DEFAULT_TTL_MS,
  HUMAN_IDENTITY_MAX_TTL_MS,
  HUMAN_IDENTITY_MIN_TTL_MS,
  HUMAN_IDENTITY_TOKEN_PREFIX,
  HUMAN_DISPLAY_NAME_MAX_LENGTH,
  HUMAN_DISPLAY_NAME_MIN_LENGTH,
  HUMAN_MAX_DEVICES_LISTED_PER_PAGE,
  HUMAN_MAX_INVITATIONS_LISTED_PER_PAGE,
  HUMAN_MAX_MEMBERS_LISTED_PER_PAGE,
  HUMAN_TOKEN_SECRET_CHAR_LENGTH,
  PROJECT_INVITATION_DEFAULT_TTL_MS,
  PROJECT_INVITATION_MAX_TTL_MS,
  PROJECT_INVITATION_MIN_TTL_MS,
  PROJECT_INVITATION_TOKEN_PREFIX
} from "@planweave-ai/collaboration-protocol/core/limits";

/** Server persistence and process-admission limits. */
export const HUMAN_OPAQUE_ID_MAX_LENGTH = 128 as const;
export const TOKEN_SHA256_HEX_LENGTH = 64 as const;
export const PROJECT_INVITATION_IDEMPOTENCY_CACHE_TTL_MS = 300_000 as const;
export const PROJECT_INVITATION_IDEMPOTENCY_CACHE_MAX_ENTRIES = 1_000 as const;
export const HUMAN_MAX_MEMBERS_PER_PROJECT = 256 as const;
export const HUMAN_MAX_OPEN_INVITATIONS_PER_PROJECT = 64 as const;
export const HUMAN_MAX_DEVICES_PER_PRINCIPAL = 32 as const;
export const HUMAN_MAX_IDENTITY_CREDENTIALS_PER_PRINCIPAL = 32 as const;
