/**
 * Collaboration IPC names are loadable by the sandboxed preload process.
 * Keep this module free of runtime collaboration-contract imports.
 */
export const collaborationInvokeChannels = {
  getCollaborationStatus: "planweave-collaboration:getStatus",
  getCollaborationOperationDiagnostics: "planweave-collaboration:getOperationDiagnostics",
  upsertCollaborationProfile: "planweave-collaboration:upsertProfile",
  removeCollaborationProfile: "planweave-collaboration:removeProfile",
  setActiveCollaborationProfile: "planweave-collaboration:setActiveProfile",
  clearActiveCollaborationProfile: "planweave-collaboration:clearActiveProfile",
  importDeviceCredential: "planweave-collaboration:importDeviceCredential",
  clearDeviceCredential: "planweave-collaboration:clearDeviceCredential",
  bootstrapCollaborationOwner: "planweave-collaboration:bootstrapOwner",
  consumeCollaborationInvitation: "planweave-collaboration:consumeInvitation",
  connectCollaborationSession: "planweave-collaboration:connectSession",
  disconnectCollaborationSession: "planweave-collaboration:disconnectSession",
  redeemCollaborationSetupCode: "planweave-collaboration:redeemSetupCode",
  recoverCollaborationIdentities: "planweave-collaboration:recoverIdentities",
  confirmCollaborationIdentityMerge: "planweave-collaboration:confirmIdentityMerge",
  connectExistingServerByOrigin: "planweave-collaboration:connectExistingServerByOrigin",
  getActiveWorkspaceConnection: "planweave-collaboration:getActiveWorkspaceConnection",
  listRememberedServerConnections: "planweave-collaboration:listRememberedServerConnections",
  forgetRememberedServerConnection: "planweave-collaboration:forgetRememberedServerConnection",
  listWorkspacePicker: "planweave-collaboration:listWorkspacePicker",
  selectWorkspaceConnection: "planweave-collaboration:selectWorkspaceConnection",
  connectWorkspaceConnection: "planweave-collaboration:connectWorkspaceConnection",
  disconnectWorkspaceConnection: "planweave-collaboration:disconnectWorkspaceConnection",
  retryWorkspaceConnection: "planweave-collaboration:retryWorkspaceConnection",
  getDeploymentGuidance: "planweave-collaboration:getDeploymentGuidance",
  copyDeploymentComposeHandoff: "planweave-collaboration:copyDeploymentComposeHandoff",
  exportDeploymentComposeBundle: "planweave-collaboration:exportDeploymentComposeBundle",
  listServerDataExportSources: "planweave-collaboration:listServerDataExportSources",
  exportServerDataArchive: "planweave-collaboration:exportServerDataArchive",
  restoreServerDataArchive: "planweave-collaboration:restoreServerDataArchive",
  validateDeploymentConnectivity: "planweave-collaboration:validateDeploymentConnectivity",
  getDesktopServerExposure: "planweave-collaboration:getDesktopServerExposure",
  setDesktopServerExposureMode: "planweave-collaboration:setDesktopServerExposureMode",
  startCollaborationPresence: "planweave-collaboration:startPresence",
  stopCollaborationPresence: "planweave-collaboration:stopPresence",
  publishCollaborationPresence: "planweave-collaboration:publishPresence",
  openWorkspaceCanvasSession: "planweave-collaboration:openWorkspaceCanvasSession",
  submitWorkspaceCanvasCommand: "planweave-collaboration:submitWorkspaceCanvasCommand",
  reconnectWorkspaceCanvasSession: "planweave-collaboration:reconnectWorkspaceCanvasSession",
  closeWorkspaceCanvasSession: "planweave-collaboration:closeWorkspaceCanvasSession",
  getWorkspaceCanvasProjection: "planweave-collaboration:getWorkspaceCanvasProjection",
  readCollaborationCanvasBindingRuntimeAvailability:
    "planweave-collaboration:readCanvasBindingRuntimeAvailability",
  initializeWorkspaceCanvasRuntime: "planweave-collaboration:initializeWorkspaceCanvasRuntime",
  resetWorkspaceCanvasRuntime: "planweave-collaboration:resetWorkspaceCanvasRuntime",
  listWorkspaceCanvasSharingCandidates:
    "planweave-collaboration:listWorkspaceCanvasSharingCandidates",
  publishWorkspaceCanvas: "planweave-collaboration:publishWorkspaceCanvas",
  downloadWorkspaceCanvasFork: "planweave-collaboration:downloadWorkspaceCanvasFork",
  getCurrentCanvasAccess: "planweave-collaboration:getCurrentCanvasAccess",
  mutateCurrentCanvasAccess: "planweave-collaboration:mutateCurrentCanvasAccess",
  setCollaborationCurrentSelection: "planweave-collaboration:setCurrentSelection",
  clearCollaborationCurrentSelection: "planweave-collaboration:clearCurrentSelection",
  getLocalCollaborationServerStatus: "planweave-collaboration:getLocalServerStatus",
  getLocalCollaborationScopeCatalog: "planweave-collaboration:getLocalScopeCatalog",
  setLocalCollaborationTrustedScopes: "planweave-collaboration:setLocalTrustedScopes",
  startLocalCollaborationServer: "planweave-collaboration:startLocalServer",
  stopLocalCollaborationServer: "planweave-collaboration:stopLocalServer",
  setLocalCollaborationLanSharing: "planweave-collaboration:setLocalLanSharing",
  listLocalCollaborationTrustedScopes: "planweave-collaboration:listLocalTrustedScopes",
  registerLocalCollaborationCurrentProject: "planweave-collaboration:registerLocalCurrentProject",
  listCollaborationMembers: "planweave-collaboration:listMembers",
  updateOwnCollaborationDisplayName: "planweave-collaboration:updateOwnDisplayName",
  listCollaborationDevices: "planweave-collaboration:listDevices",
  listCollaborationInvitations: "planweave-collaboration:listInvitations",
  createCollaborationInvitation: "planweave-collaboration:createInvitation",
  createCollaborationInvitationHandoff: "planweave-collaboration:createInvitationHandoff",
  getCollaborationInvitationSecret: "planweave-collaboration:getInvitationSecret",
  getCollaborationInvitationHandoff: "planweave-collaboration:getInvitationHandoff",
  revokeCollaborationInvitation: "planweave-collaboration:revokeInvitation",
  revokeCollaborationInvitations: "planweave-collaboration:revokeInvitations",
  removeCollaborationMember: "planweave-collaboration:removeMember",
  promoteCollaborationOwner: "planweave-collaboration:promoteOwner",
  demoteCollaborationOwner: "planweave-collaboration:demoteOwner",
  revokeCollaborationDevice: "planweave-collaboration:revokeDevice",
  listCollaborationAssignments: "planweave-collaboration:listAssignments",
  getCollaborationAssignment: "planweave-collaboration:getAssignment",
  listCollaborationEligibleAssignees: "planweave-collaboration:listEligibleAssignees",
  listCollaborationEligibleHostsBatch: "planweave-collaboration:listEligibleHostsBatch",
  getCollaborationWorkAuthority: "planweave-collaboration:getWorkAuthority",
  updateCollaborationResponsibility: "planweave-collaboration:updateResponsibility",
  updateCollaborationReviewer: "planweave-collaboration:updateReviewer",
  listCollaborationComments: "planweave-collaboration:listComments",
  listCollaborationActivity: "planweave-collaboration:listActivity",
  listCollaborationAuthorizedProjects: "planweave-collaboration:listAuthorizedProjects",
  listCollaborationAuthorizedCanvases: "planweave-collaboration:listAuthorizedCanvases",
  readCollaborationPackageSnapshot: "planweave-collaboration:readPackageSnapshot",
  createCollaborationPackageSnapshot: "planweave-collaboration:createPackageSnapshot",
  restoreCollaborationPackageSnapshot: "planweave-collaboration:restorePackageSnapshot",
  updateCollaborationAssignment: "planweave-collaboration:updateAssignment",
  createCollaborationComment: "planweave-collaboration:createComment",
  editCollaborationComment: "planweave-collaboration:editComment",
  tombstoneCollaborationComment: "planweave-collaboration:tombstoneComment",
  createCollaborationPendingAttachment: "planweave-collaboration:createPendingAttachment",
  uploadCollaborationPendingAttachment: "planweave-collaboration:uploadPendingAttachment",
  finalizeCollaborationPendingAttachment: "planweave-collaboration:finalizePendingAttachment",
  readCollaborationCommentAttachment: "planweave-collaboration:readCommentAttachment",
  listCollaborationAgentEndpoints: "planweave-collaboration:listAgentEndpoints",
  observeCollaborationRemoteOperation: "planweave-collaboration:observeRemoteOperation",
  lookupCollaborationRemoteOperation: "planweave-collaboration:lookupRemoteOperation",
  lookupWorkspaceRemoteOperation: "planweave-collaboration:lookupWorkspaceRemoteOperation",
  observeWorkspaceRemoteOperation: "planweave-collaboration:observeWorkspaceRemoteOperation",
  replayCollaborationRemoteOperationEvents: "planweave-collaboration:replayRemoteOperationEvents",
  replayWorkspaceRemoteOperationEvents:
    "planweave-collaboration:replayWorkspaceRemoteOperationEvents"
} as const;

export const collaborationStatusChangedChannel = "planweave-collaboration:statusChanged";
export const collaborationOperationDiagnosticsChangedChannel =
  "planweave-collaboration:operationDiagnosticsChanged";
export const collaborationObserverSignalChannel = "planweave-collaboration:observerSignal";
export const collaborationPresenceSignalChannel = "planweave-collaboration:presenceSignal";
export const collaborationCanvasBindingReplicaSignalChannel =
  "planweave-collaboration:canvasBindingReplicaSignal";
export const workspaceCanvasProjectionSignalChannel =
  "planweave-collaboration:workspaceCanvasProjection";
